"""
Canonical Acceptance Validator - Validates training_asset_spec at different levels
"""

from typing import Dict, Any, Tuple, List

class CanonicalAcceptanceValidator:
    """Validates training_asset_spec against AI-first canonical design criteria."""
    
    REQUIRED_METADATA = [
        'generated_at',
        'generation_mode',
        'provider',
        'model',
        'pipeline_version',
        'dominant_modality',
        'evidence_quality'
    ]
    
    @staticmethod
    def _create_result(is_valid: bool, level: str, errors: List[str], warnings: List[str]) -> Dict[str, Any]:
        return {
            "is_valid": is_valid,
            "level": level,
            "errors": errors,
            "warnings": warnings
        }

    @staticmethod
    def validate_basic(spec: Dict[str, Any]) -> Dict[str, Any]:
        """
        Level 1: Basic validation. 
        Checks if the spec is structurally sound and has essential top-level keys.
        """
        errors = []
        warnings = []
        
        required_keys = ['asset_meta', 'instructional_core']
        for key in required_keys:
            if key not in spec:
                errors.append(f"Missing required top-level key: {key}")
                
        if 'metadata' not in spec:
            warnings.append("Top-level 'metadata' block is missing (may be a legacy spec)")
            
        return CanonicalAcceptanceValidator._create_result(
            is_valid=len(errors) == 0,
            level="basic",
            errors=errors,
            warnings=warnings
        )

    @staticmethod
    def validate_canonical(spec: Dict[str, Any]) -> Dict[str, Any]:
        """
        Level 2: Canonical validation.
        Checks if the spec was generated via canonical mode with required metadata.
        """
        basic_res = CanonicalAcceptanceValidator.validate_basic(spec)
        errors = basic_res["errors"][:]
        warnings = basic_res["warnings"][:]
        
        metadata = spec.get('metadata', {})
        if not metadata:
            errors.append("canonical validation failed: top-level 'metadata' block is missing")
            return CanonicalAcceptanceValidator._create_result(False, "canonical", errors, warnings)
        
        for field in CanonicalAcceptanceValidator.REQUIRED_METADATA:
            val = metadata.get(field)
            if not val and field != 'pipeline_version':  # pipeline_version could be missing/empty but others must exist
                errors.append(f"canonical validation failed: Missing or empty required metadata field: '{field}'")
                
        mode = metadata.get('generation_mode')
        
        if mode != 'canonical':
            if mode in ('fallback', 'test', 'unknown'):
                errors.append(f"canonical validation failed: metadata.generation_mode is '{mode}', expected 'canonical'. This asset was not generated by AI and cannot be treated as a production canonical spec.")
            else:
                errors.append(f"canonical validation failed: metadata.generation_mode is '{mode}', expected 'canonical'.")
                
        provider = metadata.get('provider')
        if provider == 'non-llm' or not provider:
            errors.append(f"canonical validation failed: invalid provider '{provider}' for canonical mode. Expected an LLM provider (e.g. 'openai').")
            
        return CanonicalAcceptanceValidator._create_result(
            is_valid=len(errors) == 0,
            level="canonical",
            errors=errors,
            warnings=warnings
        )

    @staticmethod
    def validate_acceptance(spec: Dict[str, Any]) -> Dict[str, Any]:
        """
        Level 3: Acceptance validation.
        Checks semantic depth, instructional core structure, and traceability.
        """
        canonical_res = CanonicalAcceptanceValidator.validate_canonical(spec)
        errors = canonical_res["errors"][:]
        warnings = canonical_res["warnings"][:]
        
        core = spec.get('instructional_core', {})
        if not core:
            errors.append("acceptance validation failed: 'instructional_core' block is empty")
        
        chapters = core.get('chapters', [])
        if not chapters:
            errors.append("acceptance validation failed: 'instructional_core' has no chapters")
            
        has_steps = False
        for c_idx, chapter in enumerate(chapters):
            if 'chapter_id' not in chapter:
                errors.append(f"acceptance validation failed: chapter_id missing in chapter[{c_idx}]")
            for p_idx, proc in enumerate(chapter.get('procedures', [])):
                if proc.get('steps'):
                    has_steps = True
        
        if not has_steps:
            errors.append("acceptance validation failed: No actionable steps found in instructional_core")
            
        if 'source_evidence' not in spec:
            errors.append("acceptance validation failed: 'source_evidence' block is missing (required for traceability)")
            
        metadata = spec.get('metadata', {})
        modality = metadata.get('dominant_modality', 'unknown')
        quality = metadata.get('evidence_quality', 'unknown')
        
        if modality == 'weak_evidence' or quality == 'weak':
            errors.append(f"acceptance validation failed: evidence quality is '{quality}' (modality: '{modality}'). This requires human review and cannot pass automatic acceptance.")
            
        return CanonicalAcceptanceValidator._create_result(
            is_valid=len(errors) == 0,
            level="acceptance",
            errors=errors,
            warnings=warnings
        )
