"""
Phase 6 llm_training_asset_builder 修正スクリプト
"""

from pathlib import Path

builder_file = Path("src/video_asset_manualize/llm_training_asset_builder.py")
content = builder_file.read_text(encoding='utf-8')

# training_asset_spec の構造を修正
old_spec_structure = '''        training_asset_spec = {
            "schema_version": "0.1.0",
            "asset_meta": {'''

new_spec_structure = '''        training_asset_spec = {
            "asset_meta": {'''

content = content.replace(old_spec_structure, new_spec_structure)

# metadata をメタデータセクションに移動
old_metadata = '''            "metadata": {
                "schema_version": "0.1.0",
                "generated_at": now,
                "pipeline_version": "0.6.0",
                "generation_context": "LLM-based extraction",
                "review_status": "pending",
                "review_notes": "Generated by LLM; requires human review"
            }'''

new_metadata = '''            "metadata": {
                "generated_at": now,
                "pipeline_version": "0.6.0",
                "generation_context": "LLM-based extraction",
                "review_status": "pending",
                "review_notes": "Generated by LLM; requires human review"
            }'''

content = content.replace(old_metadata, new_metadata)

builder_file.write_text(content, encoding='utf-8')
print("Updated: src/video_asset_manualize/llm_training_asset_builder.py")
print("\nOK: llm_training_asset_builder.py schema structure fixed")
